services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports: [8025:8025, 1025:1025]
  postgres:
    image: postgres:13.3
    environment: [POSTGRES_PASSWORD=postgres, POSTGRES_DB=interval]
    ports: [5432:5432]
    volumes: [./data/postgres:/var/lib/postgresql/data]
